# Cloud Build configuration for Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/manga-service/backend:$BUILD_ID'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/manga-service/backend:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/manga-service/backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'manga-backend-${_ENV}'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/manga-service/backend:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--cpu'
      - '2'
      - '--memory'
      - '2Gi'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '50'
      - '--concurrency'
      - '50'
      - '--timeout'
      - '900'
      - '--service-account'
      - 'manga-service-account@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--vpc-connector'
      - 'projects/${PROJECT_ID}/locations/asia-northeast1/connectors/manga-vpc-connector'
      - '--set-env-vars'
      - 'ENV=production,DATABASE_URL=${_DATABASE_URL},REDIS_URL=${_REDIS_URL},FIREBASE_PROJECT_ID=${PROJECT_ID}'
      - '--set-secrets'
      - 'SECRET_KEY=manga-secret-key:latest'


# Build timeout
timeout: '1200s'

# Substitutions
substitutions:
  _ENV: 'prod'
  _DATABASE_URL: 'postgresql://manga_user:${_DB_PASSWORD}@${_DB_HOST}/manga_db'
  _REDIS_URL: 'redis://${_REDIS_HOST}:6379/0'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'