"""Change user.id and refresh_tokens.user_id from UUID to String for Firebase UIDs

Revision ID: 484e5481d4d6
Revises: 0e4185ca2378
Create Date: 2025-09-08 12:12:23.902136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484e5481d4d6'
down_revision: Union[str, None] = '0e4185ca2378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=128),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.String(length=128),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###