version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: comic-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: comic-ai-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_CLOUD_PROJECT=comic-ai-agent
    volumes:
      - ../backend:/app
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: comic-ai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  redis_data: