name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths: 
      - 'infrastructure/terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'prod'
        type: choice
        options:
        - prod
        - dev

env:
  PROJECT_ID: comic-ai-agent-470309
  TF_VERSION: '1.5.0'
  
jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: infrastructure/terraform/environments/${{ github.event.inputs.environment || 'prod' }}
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="project_id=${{ env.PROJECT_ID }}" \
          -var="backend_container_image=asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/manga-service/backend:latest" \
          -var="frontend_container_image=asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/manga-service/frontend:latest" \
          -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan

    - name: Output Infrastructure URLs
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "Infrastructure deployed successfully"
        terraform output